require("custom.kevin")
require("custom.plugins.mac.copilot")
require("custom.plugins.mac.indent-blankline")
require("custom.plugins.mac.null-ls")
require("custom.plugins.mac.prettier")
require("custom.plugins.mac.auto-save")
require("custom.plugins.mac.nvim-dashboard")
require("custom.plugins.mac.trouble")
require("custom.plugins.mac.harpoon")
require("custom.plugins.mac.oil")
require("custom.plugins.mac.colorizer")
require("custom.plugins.mac.dart-checkForSdkUpdates")
require("custom.plugins.mac.fzf-lua")
require("custom.plugins.mac.nvim-autopairs")
require("custom.plugins.mac.rainbow-delimiters")
require("custom.plugins.mac.nvim-tree")
require("custom.plugins.mac.nvim-ts-autotag")
require("custom.plugins.mac.drop")
require("custom.plugins.mac.render-markdown")
require("custom.plugins.mac.workspace-diagnostics")
require("custom.plugins.mac.snippet-converter")
require("custom.plugins.mac.neo-test")

return {}
