vim.g.mapleader = " "
vim.g.maplocalleader = " "

local vscode = require("vscode")

vim.keymap.set("n", "<Esc>", function()
  vscode.call("nohl")
end, { desc = "Clear search highlight" })

vim.keymap.set("n", "<C-h>", function()
  vscode.call("workbench.action.navigateLeft")
end)
vim.keymap.set("n", "<C-j>", function()
  vscode.call("workbench.action.navigateDown")
end)
vim.keymap.set("n", "<C-k>", function()
  vscode.call("workbench.action.navigateUp")
end)
vim.keymap.set("n", "<C-l>", function()
  vscode.call("workbench.action.navigateRight")
end)

vim.keymap.set("n", "<leader>sf", function()
  vscode.call("workbench.action.quickOpen")
end, { desc = "Search files" })
vim.keymap.set("n", "<leader>sg", function()
  vscode.call("workbench.action.findInFiles")
end, { desc = "Search grep" })
vim.keymap.set("n", "<leader>sr", function()
  vscode.call("workbench.action.replaceInFiles")
end, { desc = "Search replace" })
vim.keymap.set("n", "<leader>sd", function()
  vscode.call("workbench.actions.view.problems")
end, { desc = "Search diagnostics" })
vim.keymap.set("n", "<leader><leader>", function()
  vscode.call("workbench.action.showAllEditors")
end, { desc = "Search buffers" })

vim.keymap.set("n", "gd", function()
  vscode.call("editor.action.revealDefinition")
end)
vim.keymap.set("n", "gr", function()
  vscode.call("references-view.findReferences")
end)
vim.keymap.set("n", "gI", function()
  vscode.call("editor.action.goToImplementation")
end)
vim.keymap.set("n", "gD", function()
  vscode.call("editor.action.revealDeclaration")
end)
vim.keymap.set("n", "K", function()
  vscode.call("editor.action.showHover")
end)
vim.keymap.set("n", "<leader>ca", function()
  vscode.call("editor.action.quickFix")
end, { desc = "Code actions" })
vim.keymap.set("n", "<leader>rn", function()
  vscode.call("editor.action.rename")
end, { desc = "Rename" })
vim.keymap.set("n", "<leader>cf", function()
  vscode.call("editor.action.formatDocument")
end, { desc = "Format file" })
vim.keymap.set("n", "<leader>pp", function()
  vscode.call("editor.action.formatDocument")
end, { desc = "Format file" })

vim.keymap.set("n", "<leader>bn", function()
  vscode.call("workbench.action.nextEditor")
end, { desc = "Next buffer" })
vim.keymap.set("n", "<leader>bp", function()
  vscode.call("workbench.action.previousEditor")
end, { desc = "Previous buffer" })
vim.keymap.set("n", "<leader>bd", function()
  vscode.call("workbench.action.closeActiveEditor")
end, { desc = "Close buffer" })
vim.keymap.set("n", "<leader>bc", function()
  vscode.call("workbench.action.closeOtherEditors")
end, { desc = "Close other buffers" })

vim.keymap.set("n", "<leader>tt", function()
  vscode.call("workbench.action.toggleSidebarVisibility")
end, { desc = "Toggle explorer" })
vim.keymap.set("n", "<leader>tf", function()
  vscode.call("workbench.files.action.focusFilesExplorer")
end, { desc = "Focus explorer" })
vim.keymap.set("n", "<leader>xx", function()
  vscode.call("workbench.actions.view.problems")
end, { desc = "Diagnostics" })
vim.keymap.set("n", "<leader>xn", function()
  vscode.call("editor.action.marker.next")
end, { desc = "Next diagnostic" })
vim.keymap.set("n", "<leader>xp", function()
  vscode.call("editor.action.marker.prev")
end, { desc = "Previous diagnostic" })
vim.keymap.set("n", "<leader>gi", function()
  vscode.call("workbench.view.scm")
end, { desc = "Git" })
