package.loaded["elforest.palette"] = nil
local p = require("elforest.palette")

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end
vim.o.background = "dark"
vim.g.colors_name = "elforest"

local groups = {
  -- Editor UI
  Normal = { fg = p.fg, bg = p.bg },
  NormalNC = { fg = p.fg, bg = p.bg },
  NormalFloat = { fg = p.fg, bg = p.bg2 },
  FloatBorder = { fg = p.bg4, bg = p.bg2 },
  FloatTitle = { fg = p.green, bg = p.bg2, bold = true },
  Cursor = { fg = p.bg, bg = p.yellow },
  lCursor = { link = "Cursor" },
  CursorIM = { link = "Cursor" },
  TermCursor = { link = "Cursor" },
  CursorLine = { bg = p.bg1 },
  CursorColumn = { bg = p.bg1 },
  ColorColumn = { bg = p.bg1 },
  CursorLineNr = { fg = p.yellow, bold = true },
  LineNr = { fg = p.grey },
  SignColumn = { fg = p.grey, bg = p.bg },
  FoldColumn = { fg = p.grey, bg = p.bg },
  Folded = { fg = p.comment, bg = p.bg1 },
  VertSplit = { fg = p.bg4 },
  WinSeparator = { fg = p.bg4 },
  EndOfBuffer = { fg = p.bg },
  NonText = { fg = p.bg4 },
  Whitespace = { fg = p.bg3 },
  SpecialKey = { fg = p.bg4 },
  Conceal = { fg = p.grey },
  Visual = { bg = p.bg3 },
  VisualNOS = { bg = p.bg3 },
  Search = { fg = p.bg, bg = p.yellow },
  IncSearch = { fg = p.bg, bg = p.orange },
  CurSearch = { link = "IncSearch" },
  Substitute = { fg = p.bg, bg = p.magenta },
  MatchParen = { fg = p.orange, bg = p.bg3, bold = true },
  Pmenu = { fg = p.fg, bg = p.bg2 },
  PmenuSel = { fg = p.bg, bg = p.green, bold = true },
  PmenuSbar = { bg = p.bg3 },
  PmenuThumb = { bg = p.grey },
  PmenuKind = { fg = p.magenta, bg = p.bg2 },
  PmenuExtra = { fg = p.comment, bg = p.bg2 },
  WildMenu = { link = "PmenuSel" },
  StatusLine = { fg = p.fg, bg = p.bg2 },
  StatusLineNC = { fg = p.grey, bg = p.bg1 },
  TabLine = { fg = p.cyan, bg = p.bg2 },
  TabLineFill = { bg = p.bg_dim },
  TabLineSel = { fg = p.bg, bg = p.green, bold = true },
  WinBar = { fg = p.fg, bg = p.bg },
  WinBarNC = { fg = p.grey, bg = p.bg },
  Title = { fg = p.green, bold = true },
  Directory = { fg = p.blue },
  Question = { fg = p.green },
  MoreMsg = { fg = p.green },
  ModeMsg = { fg = p.yellow, bold = true },
  ErrorMsg = { fg = p.red, bold = true },
  WarningMsg = { fg = p.orange },
  QuickFixLine = { bg = p.bg3 },
  SpellBad = { sp = p.red, undercurl = true },
  SpellCap = { sp = p.yellow, undercurl = true },
  SpellLocal = { sp = p.cyan, undercurl = true },
  SpellRare = { sp = p.magenta, undercurl = true },

  -- Syntax, elflord roles in everforest tones
  Comment = { fg = p.comment, italic = true },
  Constant = { fg = p.magenta },
  String = { fg = p.magenta },
  Character = { fg = p.magenta },
  Number = { fg = p.purple },
  Float = { fg = p.purple },
  Boolean = { fg = p.purple, bold = true },
  Identifier = { fg = p.fg },
  Function = { fg = p.green },
  Statement = { fg = p.yellow },
  Conditional = { fg = p.yellow },
  Repeat = { fg = p.yellow },
  Label = { fg = p.yellow },
  Operator = { fg = p.orange },
  Keyword = { fg = p.yellow },
  Exception = { fg = p.red },
  PreProc = { fg = p.bright_magenta },
  Include = { fg = p.bright_magenta },
  Define = { fg = p.bright_magenta },
  Macro = { fg = p.bright_magenta },
  PreCondit = { fg = p.bright_magenta },
  Type = { fg = p.blue },
  StorageClass = { fg = p.yellow },
  Structure = { fg = p.blue },
  Typedef = { fg = p.blue },
  Special = { fg = p.orange },
  SpecialChar = { fg = p.orange },
  Tag = { fg = p.green },
  Delimiter = { fg = p.orange },
  SpecialComment = { fg = p.comment, bold = true },
  Debug = { fg = p.red },
  Underlined = { fg = p.blue, underline = true },
  Error = { fg = p.red, bold = true },
  Todo = { fg = p.bg, bg = p.yellow, bold = true },
  Added = { fg = p.green },
  Changed = { fg = p.blue },
  Removed = { fg = p.red },

  -- Treesitter
  ["@variable"] = { fg = p.fg },
  ["@variable.builtin"] = { fg = p.red, italic = true },
  ["@variable.parameter"] = { fg = p.fg_bright },
  ["@variable.member"] = { fg = p.cyan },
  ["@property"] = { fg = p.cyan },
  ["@constant"] = { fg = p.magenta },
  ["@constant.builtin"] = { fg = p.purple, bold = true },
  ["@module"] = { fg = p.blue },
  ["@string"] = { link = "String" },
  ["@string.escape"] = { fg = p.orange },
  ["@string.special"] = { fg = p.orange },
  ["@string.regexp"] = { fg = p.orange },
  ["@function"] = { link = "Function" },
  ["@function.builtin"] = { fg = p.green, italic = true },
  ["@function.call"] = { link = "Function" },
  ["@function.method"] = { link = "Function" },
  ["@constructor"] = { fg = p.blue },
  ["@keyword"] = { link = "Keyword" },
  ["@keyword.function"] = { fg = p.yellow },
  ["@keyword.return"] = { fg = p.yellow, bold = true },
  ["@keyword.import"] = { link = "Include" },
  ["@operator"] = { link = "Operator" },
  ["@punctuation.delimiter"] = { fg = p.orange },
  ["@punctuation.bracket"] = { fg = p.orange },
  ["@punctuation.special"] = { fg = p.orange },
  ["@type"] = { link = "Type" },
  ["@type.builtin"] = { fg = p.blue, italic = true },
  ["@tag"] = { fg = p.green },
  ["@tag.attribute"] = { fg = p.cyan },
  ["@tag.delimiter"] = { fg = p.orange },
  ["@markup.heading"] = { fg = p.green, bold = true },
  ["@markup.strong"] = { bold = true },
  ["@markup.italic"] = { italic = true },
  ["@markup.link"] = { fg = p.blue, underline = true },
  ["@markup.link.url"] = { fg = p.blue, underline = true },
  ["@markup.raw"] = { fg = p.magenta },
  ["@markup.list"] = { fg = p.orange },
  ["@comment.todo"] = { link = "Todo" },
  ["@comment.error"] = { fg = p.bg, bg = p.red, bold = true },
  ["@comment.warning"] = { fg = p.bg, bg = p.orange, bold = true },
  ["@comment.note"] = { fg = p.bg, bg = p.blue, bold = true },
  ["@lsp.type.parameter"] = { link = "@variable.parameter" },
  ["@lsp.type.property"] = { link = "@property" },
  ["@lsp.type.namespace"] = { link = "@module" },

  -- Diagnostics
  DiagnosticError = { fg = p.red },
  DiagnosticWarn = { fg = p.orange },
  DiagnosticInfo = { fg = p.blue },
  DiagnosticHint = { fg = p.cyan },
  DiagnosticOk = { fg = p.green },
  DiagnosticUnderlineError = { fg = p.red, underline = true },
  DiagnosticUnderlineWarn = { sp = p.orange, undercurl = true },
  DiagnosticUnderlineInfo = { sp = p.blue, undercurl = true },
  DiagnosticUnderlineHint = { sp = p.cyan, undercurl = true },
  DiagnosticVirtualTextError = { fg = p.red, bg = p.diff_delete },
  DiagnosticVirtualTextWarn = { fg = p.orange, bg = p.bg1 },
  DiagnosticVirtualTextInfo = { fg = p.blue, bg = p.diff_change },
  DiagnosticVirtualTextHint = { fg = p.cyan, bg = p.bg1 },
  LspReferenceText = { bg = p.bg3 },
  LspReferenceRead = { bg = p.bg3 },
  LspReferenceWrite = { bg = p.bg3, underline = true },
  LspInlayHint = { fg = p.grey, italic = true },
  LspSignatureActiveParameter = { fg = p.yellow, bold = true },

  -- Diff and git
  DiffAdd = { bg = p.diff_add },
  DiffChange = { bg = p.diff_change },
  DiffDelete = { fg = p.red, bg = p.diff_delete },
  DiffText = { bg = p.diff_text },
  GitSignsAdd = { fg = p.green },
  GitSignsChange = { fg = p.blue },
  GitSignsDelete = { fg = p.red },

  -- Telescope
  TelescopeNormal = { link = "NormalFloat" },
  TelescopeBorder = { link = "FloatBorder" },
  TelescopeTitle = { link = "FloatTitle" },
  TelescopeSelection = { bg = p.bg3 },
  TelescopeSelectionCaret = { fg = p.yellow, bg = p.bg3 },
  TelescopeMatching = { fg = p.yellow, bold = true },
  TelescopePromptPrefix = { fg = p.green },

  -- nvim-cmp
  CmpItemAbbrMatch = { fg = p.yellow, bold = true },
  CmpItemAbbrMatchFuzzy = { fg = p.yellow },
  CmpItemAbbrDeprecated = { fg = p.grey, strikethrough = true },
  CmpItemKindFunction = { fg = p.green },
  CmpItemKindMethod = { fg = p.green },
  CmpItemKindVariable = { fg = p.fg },
  CmpItemKindField = { fg = p.cyan },
  CmpItemKindProperty = { fg = p.cyan },
  CmpItemKindKeyword = { fg = p.yellow },
  CmpItemKindClass = { fg = p.blue },
  CmpItemKindSnippet = { fg = p.magenta },
  CmpItemMenu = { fg = p.comment },

  -- mini.statusline
  MiniStatuslineModeNormal = { fg = p.bg, bg = p.green, bold = true },
  MiniStatuslineModeInsert = { fg = p.bg, bg = p.yellow, bold = true },
  MiniStatuslineModeVisual = { fg = p.bg, bg = p.magenta, bold = true },
  MiniStatuslineModeReplace = { fg = p.bg, bg = p.red, bold = true },
  MiniStatuslineModeCommand = { fg = p.bg, bg = p.orange, bold = true },
  MiniStatuslineModeOther = { fg = p.bg, bg = p.cyan, bold = true },
  MiniStatuslineDevinfo = { fg = p.fg, bg = p.bg3 },
  MiniStatuslineFilename = { fg = p.fg, bg = p.bg2 },
  MiniStatuslineFileinfo = { fg = p.fg, bg = p.bg3 },
  MiniStatuslineInactive = { fg = p.grey, bg = p.bg1 },

  -- Other plugins
  WhichKey = { fg = p.green },
  WhichKeyGroup = { fg = p.blue },
  WhichKeyDesc = { fg = p.fg },
  WhichKeySeparator = { fg = p.grey },
  NvimTreeNormal = { fg = p.fg, bg = p.bg_dim },
  NvimTreeFolderName = { fg = p.blue },
  NvimTreeOpenedFolderName = { fg = p.blue, bold = true },
  NvimTreeRootFolder = { fg = p.green, bold = true },
  NvimTreeGitDirty = { fg = p.orange },
  NvimTreeGitNew = { fg = p.green },
  NvimTreeGitDeleted = { fg = p.red },
  IblIndent = { fg = p.bg2 },
  IblScope = { fg = p.bg4 },
  RainbowDelimiterRed = { fg = p.red },
  RainbowDelimiterYellow = { fg = p.yellow },
  RainbowDelimiterBlue = { fg = p.blue },
  RainbowDelimiterOrange = { fg = p.orange },
  RainbowDelimiterGreen = { fg = p.green },
  RainbowDelimiterViolet = { fg = p.magenta },
  RainbowDelimiterCyan = { fg = p.cyan },
  DashboardHeader = { fg = p.green },
  DashboardFooter = { fg = p.comment },
  DashboardDesc = { fg = p.fg },
  DashboardKey = { fg = p.yellow },
  DashboardIcon = { fg = p.cyan },
  DashboardShortCut = { fg = p.orange },
}

for name, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, name, spec)
end

for index, color in ipairs(p.ansi) do
  vim.g["terminal_color_" .. (index - 1)] = color
  vim.g["terminal_color_" .. (index + 7)] = p.brights[index]
end
