# Optional AI CLI installers for Windows.
# Writes ~/.config/wezterm/ai_clis.txt so WezTerm opens a tab for each selected CLI.

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "====================================" -ForegroundColor Cyan
Write-Host "Optional AI CLI tools" -ForegroundColor Cyan
Write-Host "====================================" -ForegroundColor Cyan
Write-Host "Answer y/n for each. Selected tools are installed and opened as WezTerm tabs on startup."
Write-Host ""

function Ask-YesNo([string]$Prompt) {
    $reply = Read-Host "$Prompt [y/N]"
    return $reply -match '^[yY]([eE][sS])?$'
}

$selected = [System.Collections.Generic.List[string]]::new()

if (Ask-YesNo "Install Cursor CLI (agent)?") {
    Write-Host "Installing Cursor CLI..." -ForegroundColor Green
    irm 'https://cursor.com/install?win32=true' | iex
    $selected.Add("agent")
} else {
    Write-Host "Skipping Cursor CLI" -ForegroundColor Gray
}

if (Ask-YesNo "Install Codex CLI?") {
    Write-Host "Installing Codex CLI..." -ForegroundColor Green
    irm https://chatgpt.com/codex/install.ps1 | iex
    $selected.Add("codex")
} else {
    Write-Host "Skipping Codex CLI" -ForegroundColor Gray
}

if (Ask-YesNo "Install Claude CLI?") {
    Write-Host "Installing Claude CLI..." -ForegroundColor Green
    irm https://claude.ai/install.ps1 | iex
    $selected.Add("claude")
} else {
    Write-Host "Skipping Claude CLI" -ForegroundColor Gray
}

$configDir = Join-Path $env:USERPROFILE ".config\wezterm"
$configFile = Join-Path $configDir "ai_clis.txt"

if (!(Test-Path $configDir)) {
    New-Item -ItemType Directory -Path $configDir -Force | Out-Null
}

$lines = @(
    "# Generated by shared/install/setup_ai_clis.ps1"
    "# One command per line; WezTerm opens a startup tab for each."
)
$lines += $selected
[System.IO.File]::WriteAllLines($configFile, $lines)

if ($selected.Count -eq 0) {
    Write-Host "No AI CLIs selected. WezTerm will not open extra AI tabs." -ForegroundColor Yellow
} else {
    Write-Host ("WezTerm will open startup tabs for: " + ($selected -join ", ")) -ForegroundColor Green
}
Write-Host "Wrote $configFile" -ForegroundColor Green
