#!/bin/bash
# Optional AI CLI installers for macOS / Linux.
# Writes ~/.config/wezterm/ai_clis.txt so WezTerm opens a tab for each selected CLI.

set -e

echo ""
echo "===================================="
echo "Optional AI CLI tools"
echo "===================================="
echo "Answer y/n for each. Selected tools are installed and opened as WezTerm tabs on startup."
echo ""

ask_yes_no() {
    local prompt="$1"
    local reply
    read -r -p "$prompt [y/N] " reply
    case "$reply" in
        [yY]|[yY][eE][sS]) return 0 ;;
        *) return 1 ;;
    esac
}

ensure_local_bin_path() {
    local local_bin="$HOME/.local/bin"
    mkdir -p "$local_bin"
    export PATH="$local_bin:$PATH"

    for rc in "$HOME/.zshrc" "$HOME/.bashrc" "$HOME/.zprofile"; do
        if [ -f "$rc" ] && ! grep -Fq '.local/bin' "$rc"; then
            echo "" >> "$rc"
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$rc"
        fi
    done
}

SELECTED=()

if ask_yes_no "Install Cursor CLI (agent)?"; then
    echo "Installing Cursor CLI..."
    ensure_local_bin_path
    curl https://cursor.com/install -fsS | bash
    SELECTED+=("agent")
else
    echo "Skipping Cursor CLI"
fi

if ask_yes_no "Install Codex CLI?"; then
    echo "Installing Codex CLI..."
    ensure_local_bin_path
    curl -fsSL https://chatgpt.com/codex/install.sh | sh
    SELECTED+=("codex")
else
    echo "Skipping Codex CLI"
fi

if ask_yes_no "Install Claude CLI?"; then
    echo "Installing Claude CLI..."
    ensure_local_bin_path
    curl -fsSL https://claude.ai/install.sh | bash
    SELECTED+=("claude")
else
    echo "Skipping Claude CLI"
fi

CONFIG_DIR="$HOME/.config/wezterm"
CONFIG_FILE="$CONFIG_DIR/ai_clis.txt"
mkdir -p "$CONFIG_DIR"

{
    echo "# Generated by shared/install/setup_ai_clis.sh"
    echo "# One command per line; WezTerm opens a startup tab for each."
    for cmd in "${SELECTED[@]}"; do
        echo "$cmd"
    done
} > "$CONFIG_FILE"

if [ "${#SELECTED[@]}" -eq 0 ]; then
    echo "No AI CLIs selected. WezTerm will not open extra AI tabs."
else
    echo "WezTerm will open startup tabs for: ${SELECTED[*]}"
fi
echo "Wrote $CONFIG_FILE"
